export const KEYBOARD_SCROLL_SPEED = 560;
export const KEYBOARD_SCROLL_INITIAL_VELOCITY = 420;
export const KEYBOARD_SCROLL_ACCELERATION = 18;
export const KEYBOARD_SCROLL_DECELERATION = 10;
export const KEYBOARD_SCROLL_MAX_FRAME = 0.05;
export const KEYBOARD_SCROLL_MIN_VELOCITY = 2;
